'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _bkp_questions

    '''<summary>
    '''labPergunta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labPergunta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rbResposta1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbResposta1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''labResposta1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labResposta1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbResposta1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbResposta1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rbResposta2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbResposta2 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''labResposta2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labResposta2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbResposta2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbResposta2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rbResposta3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbResposta3 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''labResposta3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labResposta3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbResposta3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbResposta3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''butProximo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butProximo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbCorreto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCorreto As Global.System.Web.UI.WebControls.TextBox
End Class
