'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class admCalendars

    '''<summary>
    '''butNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butNew As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''butSmart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butSmart As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divFormulario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFormulario As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlCampanha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCampanha As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlPremio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPremio As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tbDataPremio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDataPremio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''time control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents time As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbVoucher control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbVoucher As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''butCadastrar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butCadastrar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''butCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''butConfirmar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butConfirmar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlFiltroCampanha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFiltroCampanha As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlFiltroPremio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFiltroPremio As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tbFiltroInicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbFiltroInicio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbFiltroFim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbFiltroFim As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOrdenacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOrdenacao As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnFiltrar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFiltrar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Repeater1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Repeater1 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''tbPaginacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPaginacao As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''butCarregar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butCarregar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''labTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''butAnterior control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butAnterior As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''butProximo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butProximo As Global.System.Web.UI.WebControls.LinkButton
End Class
