'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class menu

    '''<summary>
    '''labNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labNome As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linkCampanhas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkCampanhas As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''menuAdm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menuAdm As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''linkUsuarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkUsuarios As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''linkEmpresas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkEmpresas As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''labScript control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labScript As Global.System.Web.UI.WebControls.Label
End Class
